# Generated by Django 3.2.3 on 2021-07-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_auto_20210706_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=264, unique=True),
        ),
    ]
